spring.application.name=Spring Boot Web Tutorial
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/ganes/OneDrive/Desktop/Java_Learning/springbootwebtutorial-personal/db
#spring.datasource.url=jdbc:h2:file:/Users/anuj/Documents/springBootWebTutorial/db
spring.datasource.username=ganesh
spring.datasource.password=Ganesh123
spring.jpa.hibernate.ddl-auto=update
